name: KiCad PCB Check

on:
  pull_request:
    paths:
      - '**/*.kicad_pcb'
    types: [opened, synchronize, reopened, assigned]

jobs:
  check-pcb:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      # Install KiCad tools (if needed)
      - name: Install KiCad
        run: |
          sudo add-apt-repository -y ppa:kicad/kicad-9.0-releases
          sudo apt update
          sudo apt install --install-recommends -y kicad
      
      # Find only PCB files named after their parent folder
      # this is written by claude tyvm (i don't know shell script and didnt wanna start writing things in python and tinkering with git et al)
      - name: Find matching PCB files
        id: find-pcb
        run: |
          # Get list of modified or added PCB files
          PCB_FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | grep '\.kicad_pcb$' | tr '\n' ' ')
          echo "Found modified KiCad PCB files: $PCB_FILES"
          echo "PCB_FILES=$PCB_FILES" >> $GITHUB_ENV
      
      # Run your KiCad PCB checks only if matching PCBs were found
      - name: Run KiCad PCB checks
        if: env.SKIP_REMAINING != 'true'
        run: |
          if [ -z "$PCB_FILES" ]; then
            echo "No PCB files were modified, nothing to check."
            exit 2
          fi
          
          for file in $PCB_FILES; do
            echo "Processing PCB file: $file"
            kicad-cli pcb drc --severity-error --exit-code-violations $file
            ls -la "$file"
